CREATE TABLE IF NOT EXISTS public.may2021
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    departure timestamp without time zone,
    "return" timestamp without time zone,
    departure_station_id SERIAL NOT NULL,
    departure_station_name character varying(100) NOT NULL ,
    return_station_id SERIAL  NOT NULL ,
    return_station_name character varying(100) COLLATE pg_catalog."default",
    covered_distance double precision,
    duration integer,
    CONSTRAINT june2021_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.june2021
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    departure timestamp without time zone,
    "return" timestamp without time zone,
    departure_station_id integer NOT NULL,
    departure_station_name character varying(100) COLLATE pg_catalog."default",
    return_station_id integer,
    return_station_name character varying(100) COLLATE pg_catalog."default",
    covered_distance double precision,
    duration integer,
    CONSTRAINT may2021_pkey PRIMARY KEY (id)
);


drop  table if exists public.may2021;


